# Generated by Django 2.2.6 on 2019-11-03 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('no', models.AutoField(max_length=255, primary_key=True, serialize=False, verbose_name='名前')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('user_id', models.CharField(max_length=255, null=True, verbose_name='ユーザーID')),
                ('site_name', models.CharField(max_length=255, verbose_name='サイト名')),
                ('inclede_category', models.CharField(max_length=255, null=True, verbose_name='カテゴリ含む')),
                ('inclede_subject', models.CharField(max_length=255, null=True, verbose_name='件名含む')),
                ('max_count', models.IntegerField(null=True, verbose_name='最大件数')),
                ('limit_day', models.IntegerField(null=True, verbose_name='日付以内')),
                ('create_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('update_at', models.DateField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoModelForm',
        ),
    ]
