# Generated by Django 2.2.6 on 2019-11-04 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20191103_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='version',
            field=models.CharField(default=1, max_length=10, verbose_name='バージョン'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='create_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='inclede_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カテゴリ含む'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='inclede_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='件名含む'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='limit_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='日付以内'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='max_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大件数'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='update_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ユーザーID'),
        ),
    ]
