# Generated by Django 2.2.6 on 2019-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20191104_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='inclede_creater',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='投稿者含む'),
        ),
    ]
